version: "3.9"
services:
  postgres:
    image: postgres:10.6
    container_name: gdk-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=unicorn_user
      - POSTGRES_PASSWORD=magical_password
      - POSTGRES_DB=rizalgowandy-gdk
    tty: true
    restart: unless-stopped

  redis_cluster: # Mimic ElastiCache with Redis Cluster Mode On
    image: grokzen/redis-cluster:5.0.12
    container_name: gdk-redis_cluster
    environment:
      - IP=0.0.0.0
    ports:
      - "7000-7005:7000-7005"
    restart: unless-stopped

  nsqlookupd:
    image: nsqio/nsq:v1.2.0
    container_name: gdk-nsqlookupd
    command: /nsqlookupd
    ports:
      - "4160:4160"
      - "4161:4161"
    restart: unless-stopped

  nsqd:
    image: nsqio/nsq:v1.2.0
    container_name: gdk-nsqd
    command: /nsqd --broadcast-address=nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - "4150:4150"
      - "4151:4151"
    restart: unless-stopped

  nsqadmin:
    image: nsqio/nsq:v1.2.0
    container_name: gdk-nsqadmin
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd
    ports:
      - "4171:4171"
    restart: unless-stopped

  redpanda: # supports kafka
    image: docker.vectorized.io/vectorized/redpanda:v21.9.5
    container_name: gdk-redpanda
    ports:
      - 9092:9092
      - 29092:29092
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - '0'
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
    restart: unless-stopped

  kafdrop: # kafka-ui
    image: obsidiandynamics/kafdrop:3.27.0
    container_name: gdk-kafdrop
    ports:
      - 9100:9000
    environment:
      - KAFKA_BROKERCONNECT=redpanda:29092
      - JVM_OPTS=-Xms32M -Xmx64M
    depends_on:
      - redpanda
    restart: unless-stopped
